export const updateTimelineItemActivitySecondsKey  = Symbol()
export const createActivityKey  = Symbol()
export const deleteActivityKey  = Symbol()
export const setActivitySecondsToCompleteKey  = Symbol()
export const periodSelectOptionsKey  = Symbol()
export const setTimelineItemActivityKey  = Symbol()
export const activitySelectOptionsKey  = Symbol()
